### ISSUE TITLE
Inject tag as version variable

### ISSUE THREAD

**Issue by evghen1** [kndpio/website#16]
## Issue Summary:
We need to show version of application in some places in docs.
## Issue Details:
Required to update website build just tag instead of push to main branch, ad using docusaurus config, define variables which could be used on frontend.
## Todo:
- [x] Update build workflow to be just built on tag push
- [x] Update workflow with tag value injection as version of custom fields.
- [x] Update CLI installation script in docs with injected version value. 

## Acceptance Criteria:
- User shall copy installation script as is and run for install alst vesion of on kndp cli
## References:
- https://docusaurus.io/docs/deployment#using-environment-variables
